"""Add defaults to Book model

Revision ID: b994ee69bee2
Revises: 6b9c061afea2
Create Date: 2026-01-25 22:29:33.645867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b994ee69bee2'
down_revision = '6b9c061afea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('history',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('history',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
