"""Add Reader table

Revision ID: dff3ab00c4e0
Revises: 87ddd371028a
Create Date: 2026-01-25 11:47:15.425348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff3ab00c4e0'
down_revision = '87ddd371028a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reader', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reader', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
